**PROGRAMMING ASSIGNMENT #2**

**Name:** Henley Lorin M. De Guzman

**Section:** 2ECE-B

In [49]:
import numpy as np

**A. REPRODUCIBLE NORMALIZATION PROBLEM** - Create a reproducible random 5×5 integer ndarray named X.

In [50]:
#Generating a 5x5 integer ndarray X
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
X

array([[48, 11, 15, 67, 21],
       [11, 41, 13, 66, 24],
       [71, 79, 53, 67, 70],
       [77, 35, 91, 19, 96],
       [35, 54, 37, 41, 17]])

In [51]:
#Calculating the mean
mean = np.mean(X)
mean

np.float64(46.36)

In [52]:
#Calculating the standard deviation
std = np.std(X)
std

np.float64(25.864075471588002)

In [53]:
#Normalizing the array using the given formula in the file
X_normalized = (X - mean) / std
X_normalized

array([[ 0.06340841, -1.36714726, -1.2124926 ,  0.79801809, -0.98051059],
       [-1.36714726, -0.20723725, -1.28981993,  0.75935442, -0.86451959],
       [ 0.95267275,  1.26198209,  0.25672675,  0.79801809,  0.91400909],
       [ 1.18465476, -0.43921926,  1.72594609, -1.05783793,  1.91926443],
       [-0.43921926,  0.29539042, -0.36189192, -0.20723725, -1.13516526]])

In [54]:
#Normalized mean and standard deviation
print("\nMean of X_normalized:", np.mean(X_normalized))
print("Standard Deviation of X_normalized:", np.std(X_normalized))


Mean of X_normalized: 0.0
Standard Deviation of X_normalized: 0.9999999999999999


In [55]:
np.save("X_normalized.npy", X_normalized)

**B. CUBES DIVISIBLE BY 4 PROBLEM** -  Create the first 100 positive integers, cube every element and reshape the result into a 10 × 10 ndarray named C.

---



In [56]:
#The first 100 positive integers, cube every element and reshape the result into a 10 × 10 ndarray named C.
C = (np.arange(1, 101) ** 3).reshape(10, 10)

In [57]:
#Using Boolean condition on C to select every cube value divisible by 4
div_by_4 = C[C % 4 == 0]
div_by_4

array([      8,      64,     216,     512,    1000,    1728,    2744,
          4096,    5832,    8000,   10648,   13824,   17576,   21952,
         27000,   32768,   39304,   46656,   54872,   64000,   74088,
         85184,   97336,  110592,  125000,  140608,  157464,  175616,
        195112,  216000,  238328,  262144,  287496,  314432,  343000,
        373248,  405224,  438976,  474552,  512000,  551368,  592704,
        636056,  681472,  729000,  778688,  830584,  884736,  941192,
       1000000])

In [58]:
#Displaying the shape of C and the number of selected elements
print("Shape of C:", C.shape)
print("\nSelected elements:", div_by_4.size)

Shape of C: (10, 10)

Selected elements: 50


In [59]:
np.save("div_by_4.npy", div_by_4)

**C. ABOVE-MEAN SQUARES PROBELM** - Create a 6 × 6 ndarray named S containing the squares of the first 36 positive integers in increasing row-major order.

In [60]:
#A 6 × 6 ndarray named S containing the squares of the first 36 positive integers in increasing row-major order.
S = (np.arange(1, 37) ** 2).reshape(6, 6)

In [61]:
#Calculating the mean
mean = np.mean(S)

In [62]:
#Calculating above_mean
above_mean = S[S > mean]

In [63]:
#Displaying S, mean, above_mean, and the number of selected elements.
print("Array S:\n", S)
print("\nMean of S (mean):", mean)
print("\nArray above_mean:", above_mean)
print("\nNumber of selected elements:", above_mean.size)

Array S:
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Mean of S (mean): 450.1666666666667

Array above_mean: [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15


In [64]:
np.save("above_mean.npy", above_mean)